# Generated by Django 3.1.3 on 2020-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wages', models.FloatField()),
                ('claims', models.FloatField(default=0)),
                ('bonus', models.FloatField(default=0)),
            ],
        ),
    ]
