# Generated by Django 3.1.3 on 2020-11-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salary_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='emp',
        ),
    ]
