# Generated by Django 3.1.3 on 2020-12-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20201204_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='wages',
        ),
    ]
