# Generated by Django 3.1.3 on 2020-12-24 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20201216_1834'),
        ('salary', '0006_auto_20201216_1509'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together={('emp_id', 'month')},
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_sal', models.FloatField(default=0)),
                ('pay_per_shift', models.FloatField(default=0)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
