# Generated by Django 3.1.3 on 2020-11-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_worksite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('id', 'name', 'doj')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.worksite'),
        ),
    ]
