# Generated by Django 3.1.3 on 2020-11-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
        ('employee', '0005_employee_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.salary'),
        ),
    ]
