# Generated by Django 3.1.3 on 2020-11-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
