# Generated by Django 3.1.3 on 2020-11-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_remove_salary_emp'),
        ('employee', '0007_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.salary'),
        ),
    ]
