# Generated by Django 3.1.3 on 2020-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20201205_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_of_emp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
