# Generated by Django 3.1.3 on 2020-12-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_remove_attendance_worksite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.FloatField(default=0)),
                ('overtime_shifts', models.IntegerField(default=0)),
                ('unrecorded_shifts', models.IntegerField(default=0)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('worksite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.worksite')),
            ],
            options={
                'unique_together': {('emp_id', 'date')},
            },
        ),
    ]
