# Generated by Django 3.1.3 on 2020-12-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_auto_20201224_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourhour',
            old_name='overtime_shifts',
            new_name='overtime_hours',
        ),
        migrations.RenameField(
            model_name='labourhour',
            old_name='unrecorded_shifts',
            new_name='unrecorded_hours',
        ),
    ]
