# Generated by Django 3.1.3 on 2020-12-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20201227_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='profpics'),
        ),
    ]
